### ISSUE TITLE
정리 

### ISSUE THREAD

**Issue by ukleon123** [Hyeon9mak/HCP_2020#12]
간단하게 정리해 봤는데 혹시 부족하거나 더 필요한 부분이 있다면 수정해 주세요 
[정리.docx](https://github.com/Hyeon9mak/HCP_2020/files/5273675/default.docx)

**Comment by Hyeon9mak** [comment]
확인했습니다.

- 'R', 'E', '할인율'이 뜻하는 바가 무엇인지 주제에 관해 아무것도  
  모르는 사람이 이해할 수 있는 수준의 풀이가 필요합니다.  
- Frozen lake 게임과 알파고의 강화학습 간의 어떤 연관관계가 있는지 부연설명이 필요합니다.  
  e.g. 매 턴마다 최적의 판단을 내리는 것을 학습시킨다.

답변 부탁드리겠습니다.

**Comment by ukleon123** [comment]
> * 'R', 'E', '할인율'이 뜻하는 바가 무엇인지 주제에 관해 아무것도
>   모르는 사람이 이해할 수 있는 수준의 풀이가 필요합니다.

R 값은 그 행동에 의해 발생한 보상(Reward)라고 생각하면 편합니다. 행동에 의해 발생하는 보상인 셈이죠 이 보상의 값이 작을수록 그 행동은 기피하게 되고 보상의 값이 커질수록 그 행동을 더 많이 시도하게 됩니다.

할인률은 미래의 보상이 더욱 많이 고려되도록 하는 값인데, 각 행동마다 할인률을 계속 곱하면서 과거에 있었던 행동은 값이 작아지도록 하고 새로 시행하는 행동은 
상대적으로 더 높은 값을 갖도록 하는 것을 의미합니다. 
결국 목표지점에 도달하는 것이 목표이기 때문에 나중의 목표값이 커져야 목표를 더 빠르게 찾아가게 되는 것이죠 

E 값은 탐색과 기존의 것을 선택할때의 확률이라고 생각하시면 됩니다. 이 확률은 학습의 정도에 따라 학습시키는 사람이 정할 수 있는 것입니다. 보통 기존의 길에 최적화되어 있을때 새로운 길을 더 찾게 하고 싶다면 이 E값을 늘려서 더 랜덤한 길을 더 많이 찾아내는 것을 볼 수 있습니다.
  
> * Frozen lake 게임과 알파고의 강화학습 간의 어떤 연관관계가 있는지 부연설명이 필요합니다.
>   e.g. 매 턴마다 최적의 판단을 내리는 것을 학습시킨다.

이 경우는 게임을 자기 스스로 진행하면서 학습시킨다로 비유하면 좋을 것 같습니다. frozen lake 게임에서의 컴퓨터도 바둑에서의 알파고도 스스로 게임의 규칙에 따라 대국을 자기 자신과 진행해 나가면서 최적화 시키고 실력이 늘어나는 것을 통해 스스로 강화학습을 진행하는 연결고리를 찾을 수 있습니다.

**Comment by Hyeon9mak** [comment]
회의 완료!
