### ISSUE TITLE
프로젝트 진행 주제 구상

### ISSUE THREAD

**Issue by Hyeon9mak** [Hyeon9mak/HCP_2020#5]
# 프로젝트 진행 주제 구상
컴퓨터정보공학부 2020학년도 2학기 고급C프로그래밍 팀 프로젝트를 진행함에 있어  
프로젝트 진행 주제를 자유롭게 구상하고 정리하여  
각자 fork된 저장소에 업로드 후 토의시간을 가지고  
선정된 아이디어를 최종적으로 Hyeon9mak/HCP_2020 저장소에 병합하는 것을 목표로 합니다.  
  
추가 의견 언제든지 부탁드립니다.
@ukleon123 @Kimhyeonjung06

**Comment by Kimhyeonjung06** [comment]
확인
